TodoMVC/TodoListMVC/TodoListMVC/Controllers/TasksController.cs
using System.Net;
using System.Web.Mvc;
using TodoListMVC.Models;
using TodoListMVC.Services;

namespace TodoListMVC.Controllers
{
    public class TasksController : Controller
    {
        private ITasksService _taskService;

        public TasksController(ITasksService taskService)
        {
            _taskService = taskService;
        }

        // GET: Tasks
        public ActionResult Index()
        {
            return View(_taskService.GetAll());
        }

        // GET: Tasks/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var task = _taskService.GetById(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // GET: Tasks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Description,Status")] Task task)
        {
            if (ModelState.IsValid)
            {
                _taskService.AddNewTask(task);
                return RedirectToAction("Index");
            }

            return View(task);
        }

        // GET: Tasks/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var task = _taskService.GetById(id);

            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // POST: Tasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Description,Status")] Task task)
        {
            if (ModelState.IsValid)
            {
                _taskService.Update(task);
                return RedirectToAction("Index");
            }
            return View(task);
        }

    }
}

TodoMVC/TodoListMVC/TodoListMVC/Controllers/UsersController.cs
using PagedList;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using TodoListMVC.Models;
using TodoListMVC.Services;

namespace TodoListMVC.Controllers
{
    public class UsersController : Controller
    {
        private IUsersService _userService;

        public UsersController(IUsersService userServices)
        {
            _userService = userServices;
        }
        // GET: Users
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult GetPaging(int? page)
        {
            var listusers = _userService.GetAll();
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return PartialView("_PartialViewUser", listusers.ToPagedList(pageNumber, pageSize));
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = _userService.GetById(id.Value);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //// GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Username,Password,Name,Address,Email,PhoneNumber,Role")] User user)
        {
            if (ModelState.IsValid)
            {
                _userService.AddNewUser(user);
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = _userService.GetById(id.Value);

            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Name,Address,Email,PhoneNumber,Role")] User user)
        {
            if (ModelState.IsValid)
            {
                _userService.Update(user);
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = _userService.GetById(id.Value);

            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _userService.DeleteUser(id);
            return RedirectToAction("Index");

        }
    }
}

TodoMVC/TodoListMVC/TodoListMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Dashboard", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
              
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @Html.ActionLink("Task", "Index", "Tasks", new { area = "" }, new { @class = "navbar-brand" })
                    }

                    @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                    {
                        <li>@Html.ActionLink("User", "Index", "Users", new { area = "" }, new { @class = "navbar-brand" })</li>
                    }

                </ul>
                <ul class="nav navbar-nav" style="float:right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Hi "+ @HttpContext.Current.User.Identity.Name,"","")</li>
                        <li>@Html.ActionLink("Sign out", "SignOut", "Home")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Sign Up", "SignUp", "Home")</li>
                        <li>@Html.ActionLink("Sign In", "Login", "Home")</li>
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>